name: CI/CD Practice

on:
  push:
    branches:
      - main  # Ejecuta el workflow en cada push a "main"
  pull_request:
    branches:
      - main  # Ejecuta el workflow en cada PR a "main"

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true


  deploy:
    runs-on: ubuntu-latest
    needs: [validate-html]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Cambia si necesitas una carpeta específica
